<?php die( 'These aren\'t the droids you\'re looking for.' );

/**
 * Extract of translatable strings from html/shortcode.html.
 */
_x( 'Practical Examples', 'html header', 'wpsso-schema-json-ld' );
_x( 'Customer Reviews', 'html header', 'wpsso-schema-json-ld' );
_x( 'Aggregate Ratings', 'html header', 'wpsso-schema-json-ld' );
_x( 'The <a href="https://wordpress.org/plugins/wpsso-schema-json-ld/">WPSSO Schema JSON-LD Markup add-on</a> provides extensive support for hundreds of Schema types and the <a href="https://wpsso.com/extend/plugins/wpsso/">WPSSO Core Premium plugin</a> can pull information from dozens of supported 3rd party plugins and service APIs. The most popular Schema properties can be customized easily in the <em>Document SSO</em> metabox, and if necessary, the <code>&#91;schema&#93;</code> shortcode can also be used to define additional (non-standard) properties and types for sections of your content.', 'html paragraph', 'wpsso-schema-json-ld' );
_x( 'PLEASE NOTE that the <code>&#91;schema&#93;</code> shortcode is meant for <strong>advanced users only</strong> and is not required for WPSSO Core and WPSSO JSON to create complete and accurate Schema JSON-LD markup for your content. You should not use the <code>&#91;schema&#93;</code> shortcode unless you\'re familiar and comfortable with <a href="https://schema.org">https://schema.org</a> markup &mdash; and have a very specific / non-standard requirement. If you use the <code>&#91;schema&#93;</code> shortcode, make sure you always validate any change with the <a href="https://search.google.com/test/rich-results">Google Rich Results Test</a> tool.', 'html paragraph', 'wpsso-schema-json-ld' );
_x( 'The <code>&#91;schema&#93;</code> shortcode can be used to define additional properties for the content. The following example defines an \'articleSection\' property for the Schema Article type. Note that all shortcode attributes are considered to be Schema property names, except for the \'prop\' and \'type\' attribute names, which have special meaning (see below).', 'html paragraph', 'wpsso-schema-json-ld' );
_x( 'The <code>&#91;schema&#93;</code> shortcode can also be used to define a Schema type for a section of content, along with using that section of content for the Schema type description and its media properties. The following example defines a section of content as a Schema Map type. Please note that the \'type\' value can be a WPSSO Schema type ID (as shown here) or a complete <a href="https://schema.org">https://schema.org</a> URL. When using the \'type\' shortcode attribute, the \'prop\' shortcode attribute is required (so the Schema type can be assigned to a Schema property). WPSSO JSON will automatically detect and include the example image in the Schema Map content.', 'html paragraph', 'wpsso-schema-json-ld' );
_x( 'By default, the <code>&#91;schema&#93;</code> shortcode merges / repaces existing Schema property values &mdash; if instead you want to <em>add</em> a new element to the Schema property array, prefix the \'prop\' attribute value with a \'+\' sign. For example, the following shortcodes will create an offers array with two price specifications (see below for additional notes on using nested shortcodes).', 'html paragraph', 'wpsso-schema-json-ld' );
_x( 'The resulting JSON-LD array:', 'html paragraph', 'wpsso-schema-json-ld' );
_x( '<strong>Please note that WordPress is not currently able to parse nested shortcodes</strong>, so the following shortcode structure is not supported by WordPress.', 'html paragraph', 'wpsso-schema-json-ld' );
_x( '<strong>The WPSSO JSON add-on <em>does</em> support nested shortcodes</strong>, but a numeric extension must be used to work around the WordPress limitation. WPSSO JSON supports up to 3 levels of nesting (by default), as the following example illustrates.', 'html paragraph', 'wpsso-schema-json-ld' );
_x( 'You can add (and maintain) customer reviews in your content manually using this example, but <strong>a much better (and more scalable) solution is to use a proper content rating / review plugin</strong>, like the <a href="https://wordpress.org/plugins/wpsso-ratings-and-reviews/">WPSSO Ratings and Reviews</a> add-on, which adds customer ratings, reviews, replies and aggregate ratings markup automatically. The WPSSO Core Premium plugin also supports ratings and reviews from the <a href="https://wordpress.org/plugins/woocommerce/">WooCommerce</a> and <a href="https://wordpress.org/plugins/wp-postratings/">WP-PostRatings</a> plugins.', 'html paragraph', 'wpsso-schema-json-ld' );
_x( 'Note that we\'re using Schema type IDs from WPSSO in this example &mdash; using <code>type="review"</code> is the same as using <code>type="https://schema.org/Review"</code>. Also note the use of a leading "+" sign in the first <code>&#91;schema&#93;</code> shortcode \'prop\' attribute &mdash; this tells WPSSO JSON to add this property as an array, so several reviews can be included this way. WPSSO JSON handles nested shortcodes, but WordPress does not, so nested shortcodes must be numbered for WordPress (schema, schema_1, schema_2, etc.). Don\'t forget to terminate the shortcode enclosure &mdash; it can be easy to forget that closing <code>&#91;/schema&#93;</code> tag. ;-)', 'html paragraph', 'wpsso-schema-json-ld' );
_x( 'Again, you can add (and maintain) aggregate rating values in your content manually using this example, but <strong>a much better (and more scalable) solution is to use a proper content rating / review plugin</strong>. ;-) And in case you\'re using a non-supported rating / review plugin &mdash; that saves aggregate rating values in post meta &mdash; instead of using a shortcode, you can also use a <a href="https://wpsso.com/docs/plugins/wpsso-schema-json-ld/notes/developer/filters/examples/modify-the-aggregaterating-property/">plugin filter to update the Schema aggregateRating property value</a>.', 'html paragraph', 'wpsso-schema-json-ld' );
